### ISSUE TITLE
Clean dataset.csv file

### ISSUE THREAD

**Issue by mathieudpnt** [Project-OSmOSE/OSEkit#151]
keep project / dataset / spectro_dur / sr only

**Comment by ElodieENSTA** [comment]
Final structure is:
| path | dataset | spectro_duration | dataset_sr | file_type |
|---|---|---|---|---|
| Campaign/TP_MAHY | TP_MAHY |10 | 128000 | .wav |

This is the base structure understood by APLOSE, it can be filled with aditionnal columns
