### ISSUE TITLE
dataset build not working when not proprietary of audio files

### ISSUE THREAD

**Issue by mathieudpnt** [Project-OSmOSE/OSEkit#211]
When trying to build a dataset on `data_uploader` notebook from audio files uploaded from someone else, i get a permission error

![image](https://github.com/user-attachments/assets/803a46ba-bbbe-489d-9c1f-c97ff3c29d53)

**Comment by Gautzilla** [comment]
Seems like we are trying to **change the folder permissions** only to be able to write in it, without checking first if we **do already have** the right to write in it.

I'd use a util function to do both subsequently, e.g.

```py
def change_permissions_if_writing_not_permitted(path: Path):
    if os.access(path, os.W_OK):
        return

    try:
        os.chmod(path, DPDEFAULT)
    except PermissionError:
        raise PermissionError(f"You do not have the permission to write to {p}, nor to change its permissions.")
```

I think it could do the trick
