### ISSUE TITLE
Reshaped files doesn't range up to datetime_end when concat is set to False

### ISSUE THREAD

**Issue by Gautzilla** [Project-OSmOSE/OSEkit#226]
# Description

I'm trying to reshape a dataset that has 2 audio files:

|filename|timestamp|duration|
|:---|---:|---:|
|7189.230405144906.wav|2023-04-05T14:49:06.000+0000|3600|
|7189.230405174906.wav|2023-04-05T17:49:06.000+0000|3600|

The reshaped audio should be 60s-long, start within the first original audio time period, and stop within the second original audio time period:

|spectro_duration|datetime_begin|datetime_end|
|:---:|:---:|:---:|
|60|2023-04-05T15:30:00.000+0000|2023-04-05T18:00:00.000+0000|

## Expected output

I'd want the reshaped audio to cover the specified range:

|filename|timestamp|
|:---|---:|
2023_04_05_15_30_00.wav|2023-04-05T15:30:00.000000+0000
2023_04_05_15_31_00.wav|2023-04-05T15:31:00.000000+0000
2023_04_05_15_32_00.wav|2023-04-05T15:32:00.000000+0000
2023_04_05_15_33_00.wav|2023-04-05T15:33:00.000000+0000
2023_04_05_15_34_00.wav|2023-04-05T15:34:00.000000+0000
2023_04_05_15_35_00.wav|2023-04-05T15:35:00.000000+0000
2023_04_05_15_36_00.wav|2023-04-05T15:36:00.000000+0000
2023_04_05_15_37_00.wav|2023-04-05T15:37:00.000000+0000
2023_04_05_15_38_00.wav|2023-04-05T15:38:00.000000+0000
2023_04_05_15_39_00.wav|2023-04-05T15:39:00.000000+0000
2023_04_05_15_40_00.wav|2023-04-05T15:40:00.000000+0000
2023_04_05_15_41_00.wav|2023-04-05T15:41:00.000000+0000
2023_04_05_15_42_00.wav|2023-04-05T15:42:00.000000+0000
2023_04_05_15_43_00.wav|2023-04-05T15:43:00.000000+0000
2023_04_05_15_44_00.wav|2023-04-05T15:44:00.000000+0000
2023_04_05_15_45_00.wav|2023-04-05T15:45:00.000000+0000
2023_04_05_15_46_00.wav|2023-04-05T15:46:00.000000+0000
2023_04_05_15_47_00.wav|2023-04-05T15:47:00.000000+0000
2023_04_05_15_48_00.wav|2023-04-05T15:48:00.000000+0000
2023_04_05_15_49_00.wav|2023-04-05T15:49:00.000000+0000
2023_04_05_17_49_00.wav|2023-04-05T17:49:00.000000+0000
2023_04_05_17_50_00.wav|2023-04-05T17:50:00.000000+0000
2023_04_05_17_51_00.wav|2023-04-05T17:51:00.000000+0000
2023_04_05_17_52_00.wav|2023-04-05T17:52:00.000000+0000
2023_04_05_17_53_00.wav|2023-04-05T17:53:00.000000+0000
2023_04_05_17_54_00.wav|2023-04-05T17:54:00.000000+0000
2023_04_05_17_55_00.wav|2023-04-05T17:55:00.000000+0000
2023_04_05_17_56_00.wav|2023-04-05T17:56:00.000000+0000
2023_04_05_17_57_00.wav|2023-04-05T17:57:00.000000+0000
2023_04_05_17_58_00.wav|2023-04-05T17:58:00.000000+0000
2023_04_05_17_59_00.wav|2023-04-05T17:59:00.000000+0000

## Actual output

Only the files that **start within** the expected time range are processed, and only **one** reshaped file is output:

|filename|timestamp|
|:---|---:|
|2023_04_05_17_49_06.wav|2023-04-05T17:49:06.000000+0000|

## Remark

The output is as expected if I set the concat attribute to True:

```py
dataset.concat = True
dataset.initialize(...) # Everything works fine here
```

# Code to reproduce

```py
import os
os.umask(0o002)
import sys
from pathlib import Path
from OSmOSE import Dataset, Spectrogram
from OSmOSE.utils.core_utils import display_folder_storage_info, list_not_built_dataset

path_osmose_home = Path(r"/home/datawork-osmose/")
path_osmose_dataset = path_osmose_home / "dataset"

# display_folder_storage_info(dir_path=path_osmose_home)

project_name = "tests_Gauthier"
dataset_name = "small_dataset"

date_template = "%y%m%d%H%M%S"

dataset = Dataset(
    dataset_path=Path(path_osmose_dataset, project_name, dataset_name),
    gps_coordinates=(0,0),
    depth=0,
    owner_group="gosmose",
    local=False,
    timezone="+0000",
)

dataset.build(force_upload=True, date_template=date_template)

dataset = Spectrogram(
    dataset_path=Path(path_osmose_dataset, project_name, dataset_name),
    owner_group="gosmose",
    local=False,
)

dataset.batch_number = 1
dataset.concat = False
dataset.dataset_sr = 500  # Hz
dataset.spectro_duration = 60  # seconds

dataset.initialize(
    env_name=sys.executable.replace("/bin/python", ""),
    force_init=True,
    datetime_begin="2023-04-05T15:30:00+0000",
    datetime_end="2023-04-05T18:00:00+0000",
)
```

**Comment by mathieudpnt** [comment]
This issue has been solved with #227
