### ISSUE TITLE
Create spectrograms without generating new wavs

### ISSUE THREAD

**Issue by Rumengol** [Project-OSmOSE/OSEkit#35]
The datasets might be very large, and if we need only the images, it is superfluous to write all wav files.
It should be possible to load and transform the wav in RAM and only write the resulting spectrogram.

**Comment by mathieudpnt** [comment]
Hi @Rumengol ! I know you don't work anymore with us but could you tell me about this issue ? Do you think it's easily doable ? Thanks :)
